### ISSUE TITLE
Feature req: Settings menu

### ISSUE THREAD

**Issue by ItsNilDev** [blankRiot96/web-browser#8]
![image](https://user-images.githubusercontent.com/61497342/125825941-e09cd089-672e-41b8-87e0-51edd50c1399.png)
We need something like this

**Comment by blankRiot96** [comment]
Interesting, we do, you can add that if you like, your issue number is 8 btw. So when making a branch you would need to do `feature/fix-issue-8`

Thanks for contributing!
